### ISSUE TITLE
Using Classical Loops for Processing instead of forEach

### ISSUE THREAD

**Issue by XavierSchiller** [XavierSchiller/OsuIndiaBotJS#1]
Apparently, Classical Loops are much faster to execute than forEach Loops. Might speed up performance.

**Comment by sabarnac** [comment]
This is only valid when micro-benching. You see no benefits in the real world. And the reasons for this speedup is because `forEach` does a lot more checking for you.

Stick with `forEach`. It's easier to read and understand, and makes the code less polluted and simpler.

**Comment by XavierSchiller** [comment]
I forgot to close this issue, but it wasn't due to the loops, but due to the immense amounts of `await` requests per loop. #2 should make sense now.
